### ISSUE TITLE
Not working on Gazebo 9

### ISSUE THREAD

**Issue by jmarrr** [yukkysaito/vehicle_model#4]
Hi, this perfectly works on Gazebo 7 but not on Gazebo 9 I ran `roslaunch vehicle_model world_test.launch` or `roslaunch vehicle_model gazebo9_citysim.launch` but this error pop up:

```
launch
... logging to /home/overlapjho/.ros/log/0730594e-16cf-11e9-b4be-d8cb8a9639b0/roslaunch-Jhomar-4415.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

inconsistent namespace redefinitions for xmlns:xacro:
 old: http://ros.org/wiki/xacro
 new: http://www.ros.org/wiki/xacro (/home/overlapjho/catkin_ws/src/vehicle_sim/sensor_model/velodyne/velodyne_description/urdf/HDL-32E.urdf.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://ros.org/wiki/xacro
 new: http://www.ros.org/wiki/xacro (/home/overlapjho/catkin_ws/src/vehicle_sim/sensor_model/velodyne/velodyne_description/urdf/VLP-16.urdf.xacro)
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/sensor_model/camera/camera_description/urdf/monocular_camera.xacro
included from: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/sensor_model/imu/imu_description/urdf/imu.xacro
included from: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
redefining global property: pi
when processing file: /home/overlapjho/catkin_ws/src/vehicle_sim/vehicle_model/urdf/vehicle.xacro
xacro.py is deprecated; please use xacro instead
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 306, in main
    p.start()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 268, in start
    self._start_infrastructure()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 217, in _start_infrastructure
    self._load_config()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/parent.py", line 132, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/config.py", line 451, in load_config_default
    loader.load(f, config, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 749, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 721, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 685, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 95, in call
    return f(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 589, in _include_tag
    inc_filename = self.resolve_args(tag.attributes['file'].value, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 183, in resolve_args
    return substitution_args.resolve_args(args, context=context.resolve_dict, resolve_anon=self.resolve_anon)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 370, in resolve_args
    resolved = _resolve_args(resolved, context, resolve_anon, commands)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 383, in _resolve_args
    resolved = commands[command](resolved, a, args, context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 151, in _find
    source_path_to_packages=source_path_to_packages)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/substitution_args.py", line 197, in _find_executable
    full_path = _get_executable_path(rp.get_path(args[0]), path)
  File "/usr/lib/python2.7/dist-packages/rospkg/rospack.py", line 203, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
ResourceNotFound: gazebo_ros
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/overlapjho/catkin_ws/src
ROS path [2]=/opt/ros/kinetic/share
```

**Comment by jmarrr** [comment]
Since I had previously installed gazebo7 I need to reinstall gazebo pkgs ```sudo apt-get install ros-$ROS_DISTRO-gazebo9-ros-pkgs```
